config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'pages#home'
  get 'components', to: 'pages#components'
  get 'cities/results', to: 'cities#results'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :cities, only: [:show] do
    resources :city_comments, only: [:new, :create]
    resources :bookmarks, only: :create
  end
  
  resources :searches, only: [:new, :create] do
    member do
      patch 'refresh', to: "searches#refresh"
    end
  end
  
  #definir le destroy
  delete 'bookmarks/:id', to: 'bookmarks#destroy', as: :delete_bookmark
  
  namespace :admin do
    resources :users, only: [:show]
    patch 'update/usercity/:city_id', to: 'users#update_city', as: :update_usercity
    get 'tasks', to: 'users#tasks'
    resources :city_comments, only: [] do
      resources :answers, only: [:new, :create]
    end
  end
end

app/views/shared/_city_age_criterion.html.erb
<div class="criterion">
  <div class="mr-3">
    <i class="fas fa-id-badge"></i>
  </div>
  <div>
    <span class="criterion-number"><%= item.max_age_population_rate.round %> %</span><br>
    <span class="text-muted" style="font-size: 0.9rem;">
      <%= item.max_age_population_range %>
    </span>
  </div>
</div>

app/views/shared/_city_card.html.erb
<% city_card_link = defined?(card_link) ? card_link : city_path(item) %>
<%= link_to city_card_link do %>
  <div class="default-card card-city m-3" style="background-image: url(
      <% if item.photos.attached? %>
        <%= cloudinary_url(item.photos.first.key, quality: :auto, crop: :fill) %>
      <% else %>
        <%= asset_url('city_card_template.svg') %>
      <% end %>
    )">
    <span><%= item.name %></span>
  </div>
<% end %>

app/views/shared/_city_coastline_criterion.html.erb
<div class="criterion">
  <div class="mr-3">
    <i class="fas fa-water"></i>
  </div>
  <div>
    <span class="criterion-number">Mer / Lac</span><br>
    <span class="text-muted" style="font-size: 0.9rem;">à proximité</span>
  </div>
</div>

app/views/shared/_city_description.html.erb
<div class="mt-4 p-3" style="font-size: 0.9rem;">
  <% if search.environment == "montagne" %>
    <em><%= item.mountain %></strong></em><br>
  <% end %>
  <div>
    <%= "#{item.description.squish.truncate_words(13, omission: "...")}" || 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum animi...'%>
  </div>
  <div class="mt-1">
    <%= link_to 'En savoir plus', city_path(item) %>
  </div>
</div>

app/views/shared/_city_job_criterion.html.erb
<div class="criterion<%= " best" if defined?(best) && best == item %>">
  <div class="mr-3">
    <i class="fas fa-briefcase"></i>
  </div>
  <p class="mb-0">
  <% if search %>
    <span class="criterion-number"><%= item.job_ads || 0 %></span> offres<br>
    <span class="text-muted" style="font-size: 0.9rem;"><%= search.job_title %></span>
  <% else %>
    <span class="criterion-number"><%= number_with_delimiter(item.unemployment_rate, separator: ",") %> %</span><br>
    <span class="text-muted" style="font-size: 0.9rem;">Chômage</span>
  <% end %>
  </p>
</div>

app/views/shared/_city_link.html.erb
<div class="text-center mt-4 p-3">
  <%= link_to 'Voir la ville', city_path(item), class: 'btn btn-primary' %>
</div>

app/views/shared/_city_moutain_criterion.html.erb
<div class="criterion">
  <div class="mr-3">
    <i class="fas fa-moutain"></i>
  </div>
  <div>
    <span class="criterion-number">En montagne</span><br>
    <span class="text-muted" style="font-size: 0.9rem;"><%= item.mountain %></span>
  </div>
</div>

app/views/shared/_city_region_name.html.erb
<div class="region-name">
  <span class="tag yellow-tag"><%= item.region_name %></span>
</div>

app/views/shared/_city_seo.html.erb
<% content_for :meta_title, "#{@city.name} - Avis et questions pour changer de vie" %>
<% content_for :meta_description, @city.description %>
<% content_for :meta_image, cl_image_path(@city.photos.first.key) %>

app/views/shared/_city_type_homes_criterion.html.erb
<div class="criterion">
  <div class="mr-3">
    <i class="fas fa-building"></i>
  </div>
  <div>
    <span class="criterion-number"><%= item.max_type_of_homes_rate.round %> %</span><br>
    <span class="text-muted" style="font-size: 0.9rem;">
      <%= item.max_type_of_homes_category %>
    </span>
  </div>
</div>

app/views/shared/_city_wage_criterion.html.erb
<div class="criterion">
  <div class="mr-3">
    <i class="fas fa-wallet"></i>
  </div>
  <div>
    <span class="criterion-number"><%= number_with_delimiter(item.net_hourly_wage, separator: ",") %> €</span><br>
    <span class="text-muted" style="font-size: 0.9rem;">Salaire net / h</span>
  </div>
</div>

app/views/shared/_city_weather_criterion.html.erb
<div class="criterion<%= " best" if defined?(best) && best == item %>">
  <div class="mr-3">
    <i class="fas fa-cloud-sun"></i>
  </div>
  <div>
    <% if item.rain_days %>
      <span class="criterion-number"><%= item.rain_days.round %></span> jours de pluie<br>
    <% end %>
    <% if item.sun_hours %>
      <span class="criterion-number"><%= number_with_delimiter(item.sun_hours, delimiter: " ") %></span> heures de soleil
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 <%= notice["class"] %>" role="alert">
    <% if notice["body"] %>
      <%= notice["body"] %>
    <% else %>
      <%= notice %>
    <% end %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-nextcity <%= @homepage ? 'navbar-transparent' : 'navbar-purple' %>">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.searches.present? %>
          <li class="nav-item active d-flex align-items-center mr-4">
            <%= link_to cities_results_path do %>
              <i class="fas fa-search-location navbar-icon"></i>
            <% end %>
          </li>
        <% end %>
        <li class="nav-item d-flex align-items-center mr-4">
          <%= link_to "#" do %>
            <i class="far fa-envelope navbar-icon" style="font-size: 2rem"></i>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <img class="avatar dropdown-toggle " id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= cloudinary_url(current_user.photo.key, quality: :auto, crop: :fill) %>">
          <% else %>
            <%= image_tag "avatar-template.png", class: "avatar dropdown-toggle ", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mon compte", admin_user_path(current_user), class: "dropdown-item" %>
            <% if current_user.searches.present? && current_user.city %>
              <%= link_to "Mon guide", admin_tasks_path, class: "dropdown-item" %> 
            <% end %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <div>
          <%= link_to "Se connecter", new_user_session_path, class: "btn btn-light" %>
          <%= link_to "Créer un compte", new_user_registration_path, class: "btn btn-primary" %>
        </div>
      <% end %>
    </ul>
  </div>
</div>