config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'pages#home'
  get 'components', to: 'pages#components'
  get 'cities/results', to: 'cities#results'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :cities, only: [:show] do
    resources :city_comments, only: [:new, :create]
    resources :bookmarks, only: :create
  end
  
  resources :searches, only: [:new, :create] do
    member do
      patch 'refresh', to: "searches#refresh"
    end
  end
  
  #definir le destroy
  delete 'bookmarks/:id', to: 'bookmarks#destroy', as: :delete_bookmark
  
  namespace :admin do
    resources :users, only: [:show]
    patch 'update/usercity/:city_id', to: 'users#update_city', as: :update_usercity
    get 'tasks', to: 'users#tasks'
    resources :city_comments, only: [] do
      resources :answers, only: [:new, :create]
    end
  end
end

app/models/city.rb
class City < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  # searchkick
  has_many :users
  has_many :city_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many_attached :photos
  serialize :geo_shape, Hash

  geocoded_by :address

  def max_age_population_rate
    [population_0_to_25_years_rate, population_25_to_64_years_rate, population_65_years_and_more_rate].max
  end

  def max_age_population_range
    case max_age_population_rate
    when population_0_to_25_years_rate then "Moins de 25 ans"
    when population_25_to_64_years_rate then "Entre 25 et 64 ans"
    when population_65_years_and_more_rate then "Plus de 64 ans"
    end
  end

  def max_type_of_homes_rate
    [flats_rate, houses_rate].max
  end

  def max_type_of_homes_category
    case max_type_of_homes_rate
    when flats_rate then "Appartements"
    when houses_rate then "Maisons"
    end
  end

  def tourism_range
    if tourism_structures_number < 60
      "Peu touristique"
    elsif tourism_structures_number < 2_000
      "Touristique"
    elsif tourism_structures_number < 90_000
      "Très touristique"
    else
      ""
    end
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  before_action :check, only: :results
  # skip_after_action :verify_authorized, only: :results

  def show
    @city = City.friendly.find(params[:id])
    @comments = @city.city_comments.with_answer
    @comment = CityComment.new
    if user_signed_in?
      @search = current_user.searches.last
      @has_current_bookmark = current_user.bookmark_for(@city).present?
      if @has_current_bookmark
        @bookmark = current_user.bookmark_for(@city)
      else
        @bookmark = Bookmark.new
      end
    end
    authorize @city

    @markers = [{ lat: @city.latitude, lng: @city.longitude }]
    # @city_coordinates = JSON.parse(@city.geo_shape)["coordinates"]
    @city_coordinates = @city.geo_shape
    @disable_container = true
  end

  def results
    # City.reindex
    @search = current_user.searches.last
    @cities = @search.cities_result
    @cities.map { |city| authorize city }
    @disable_container = true
    @disable_margins = true
  end

  def check
    return redirect_to root_path, notice: "Vous devez d'abord faire une recherche en cliquant sur 'Inspirez-moi'" if current_user.searches.empty?
  end
end

app/views/cities/_city_banner.html.erb
<div class="banner">
  <div class="container">
    <p class="badge"><%= @city.name %></p class="badge">
  </div>
</div>

app/views/cities/results.html.erb
<% content_for :meta_title, "Les villes de votre choix" %>
<% content_for :meta_description, "Choisissez les villes qui vous plaisent" %>

<!-- Title & Buttons -->
<section class="py-4" style="background-color: #F2F2F2; margin-top: 3.6rem;">
  <div class="container d-flex justify-content-between">
    <h1>3 villes sélectionnées pour vous</h1>
    <div class="d-flex">
      <button id="search-resume-btn" class="round-btn mr-2">
        <i class="fas fa-user"></i>
      </button>
      <%= link_to refresh_search_path(@search), method: :patch, remote: true do %>
        <button id="refresh-btn" class="round-btn mr-2">
          <i class="fas fa-sync-alt"></i>
        </button>
      <% end %>
      <button id="criteria-btn" class="round-btn">
        <i class="fas fa-sliders-h"></i>
      </button>
    </div>
  </div>
</section>
<!-- Title -->

<div class="container">

  <!-- Search resume -->
  <section id="search-resume">
    <div class="d-flex align-items-center">
      <h2 class="mb-0 mt-2" style="width: 160px">Votre recherche</h2>
      <div class="d-flex flex-wrap">
        <div class="tag light-purple-tag"><i class="fas fa-check-circle"></i> <%= @search.job_title.capitalize %></div>
        <div class="tag light-purple-tag"><i class="fas fa-check-circle"></i> <%= @search.environment.capitalize %></div>
        <div class="tag light-purple-tag"><i class="fas fa-check-circle"></i>
          <% if @search.city_type == "urbain" %>
            <%= "#{@search.city_type.capitalize} : #{@search.city_size} ville" %>
          <% else %>
            <%= "#{@search.city_type.capitalize}" %>
          <% end %>
        </div>
        <div class="tag light-purple-tag"><i class="fas fa-check-circle"></i> <%= "#{@search.home_type.capitalize} #{@search.home_category.upcase} de #{@search.home_size} m² pour #{@search.home_budget} €" %></div>
      </div>
    </div>
  </section>
  <!-- Search resume -->

  <!-- Criteria selection -->
  <section id="criteria">
    <div class="d-flex align-items-center">
      <h2 class="mb-0 mt-2" style="width: 160px">Critères</h2>
      <div>
        <button class="btn btn-primary criterion-btn">Emploi</button>
        <button class="btn btn-primary criterion-btn">Logement</button>
        <button class="btn btn-primary criterion-btn">Météo</button>
        <button class="btn btn-outline-primary criterion-btn">Internet</button>
        <button class="btn btn-outline-primary criterion-btn">Tourisme</button>
      </div>
    </div>
  </section>
  <!-- Criteria selection -->

  <!--Cities comparison -->
  <section class="my-5">

    <div class="results">
      <%= render partial: "shared/city_region_name", collection: @cities, as: :item %>
    </div>
    <!--City img -->
    <div class="results">
      <%= render partial: "shared/city_card", collection: @cities, as: :item %>
    </div>
    <!--City img -->

    <!--City description -->
    <div class="results mb-3">
      <%= render partial: "shared/city_description", collection: @cities, as: :item, locals: { search: @search } %>
    </div>
    <!--City description -->

    <!-- Job criterion -->
    <div id="emploi-criterion" class="criterion-line show">
      <hr>
      <div class="results">
        <%= render partial: "shared/city_job_criterion", collection: @cities, as: :item, locals: { search: @search, best: @cities.max_by(&:job_ads) } %>
      </div>
    </div>
    <!-- Job criterion -->

    <!-- Home criterion -->
    <div id="logement-criterion" class="criterion-line show">
      <hr>
      <div class="results">
        <%= render partial: "shared/city_home_criterion", collection: @cities, as: :item, locals: { search: @search, best: @cities.min_by(&:flats_rental_price) } %>
      </div>
    </div>
    <!-- Home criterion -->

    <!-- Weather criterion -->
    <div id="météo-criterion" class="criterion-line show">
      <hr>
      <div class="results">
        <%= render partial: "shared/city_weather_criterion", collection: @cities, as: :item, locals: { best: @cities.min_by(&:rain_days) } %>
      </div>
    </div>
    <!-- Weather criterion -->

    <!-- Internet criterion -->
    <div id="internet-criterion" class="criterion-line">
      <hr>
      <div class="results">
        <%= render partial: "shared/city_internet_criterion", collection: @cities, as: :item, locals: { best: @cities.max_by(&:ftth_homes_rate) } %>
      </div>
    </div>
    <!-- Internet criterion -->

    <!-- Tourism criterion -->
    <div id="tourisme-criterion" class="criterion-line">
      <hr>
      <div class="results">
        <%= render partial: "shared/city_tourism_criterion", collection: @cities, as: :item, locals: { best: @cities.max_by(&:tourism_structures_number) } %>
      </div>
    </div>
    <!-- Tourism criterion -->

    <!-- City link -->
    <div id="city-links" class="results">
      <%= render partial: "shared/city_link", collection: @cities, as: :item %>
    </div>
    <!-- City link -->

  </section>
  <!--Cities comparison -->

</div>

app/views/cities/show.html.erb
<%= render "shared/city_seo", city: @city %>

<div class="container">
  <div class="row">
    <div class="col-12 col-md-7">
      <section>
        <div id="header">
          <h2><%= @city.name %></h2>
          <% if user_signed_in? %>
            <div id="heart-block">
              <% if @has_current_bookmark %>
                <%= link_to delete_bookmark_path(@bookmark), method: :delete, remote: true do %>
                  <div class="heart is-active"></div>
                <% end %>
              <% else %>
                <%= link_to city_bookmarks_path(@city.id), method: :post, remote: true do %>
                <div class="heart"></div>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>

        <%= @city.description.to_s.gsub(/\n/, '<br/>').html_safe %>

      </section>

      <section class="mt-4">

        <h5>Informations</h5>

        <div class="d-flex flex-wrap mt-2">

        <% if @search || @city.unemployment_rate %>
          <div class="city-badge">
            <% if @search %>
              <div class="default-badge <%= @city.job_ads && @city.job_ads.positive? ? "success-badge" : "danger-badge" %>"></div>
            <% end %>
            <%= render "shared/city_job_criterion", item: @city, search: @search %>
          </div>
        <% end %>

        <% if @city.flats_rental_price %>
          <div class="city-badge">
            <% if @search %>
              <div class="default-badge <%= (@city.flats_rental_price * @search.home_size) < @search.home_budget ? "success-badge" : "danger-badge" %>"></div>
            <% end %>
            <%= render "shared/city_home_criterion", item: @city, search: @search %>
          </div>
        <% end %>

        <% if @city.net_hourly_wage %>
          <div class="city-badge">
            <%= render "shared/city_wage_criterion", item: @city %>
          </div>
        <% end %>

        <% if @city.coastline %>
          <div class="city-badge">
            <% if @search && @search.environment == "littoral" %>
              <div class="default-badge success-badge"></div>
            <% end %>
            <%= render "shared/city_coastline_criterion", item: @city %>
          </div>
        <% end %>

        <% if !(@city.mountain == '') %>
          <div class="city-badge">
            <%= render "shared/city_mountain_criterion", item: @city %>
          </div>
        <% end %>

        <% if @city.rain_days || @city.sun_hours %>
          <div class="city-badge">
            <%= render "shared/city_weather_criterion", item: @city %>
          </div>
        <% end %>

        <% if @city.tourism_structures_number %>
          <div class="city-badge">
            <%= render "shared/city_tourism_criterion", item: @city %>
          </div>
        <% end %>

        <% if @city.ftth_homes_rate %>
          <div class="city-badge">
            <%= render "shared/city_internet_criterion", item: @city %>
          </div>
        <% end %>

        <% if @city.max_age_population_rate %>
          <div class="city-badge">
            <%= render "shared/city_age_criterion", item: @city %>
          </div>
        <% end %>

        <% if @city.max_type_of_homes_rate %>
          <div class="city-badge">
            <%= render "shared/city_type_homes_criterion", item: @city %>
          </div>
        <% end %>

        </div>

        <% if @search %>
          <div class="d-flex align-items-center mt-4">
            <div class="d-flex align-items-center mr-3">
              <div class="default-badge success-badge mr-2"></div> Adapté à votre recherche
            </div>
            <div class="d-flex align-items-center mr-3">
              <div class="default-badge danger-badge mr-2"></div> Non adapté
            </div>
          </div>

          <% if @search.environment == "littoral" && !@city.coastline %>
            <div class="d-flex align-items-center mt-2">
              <i class="fas fa-exclamation-triangle mr-3" style="color: #ee2d48"></i>
              <span>Contrairement à vos souhaits, cette ville n'est pas située à proximité de la mer ou d'un lac.</span>
            </div>
          <% end %>
        <% end %>

      </section>
        
      <% if @comments.present? || (user_signed_in? && current_user.ask_question?(@city)) %>
        
        <section class="mt-4">

          <h5>Les réponses à vos questions</h5>

          <% if @comments.present? %>

              <div class="accordion mt-4" id="accordionExample">
                <% @comments.each do |comment| %>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="heading<%= comment.id %>">
                    <button class="accordion-button collapsed" type="button" data-toggle="collapse" data-target="#collapse<%= comment.id %>" aria-expanded="false" aria-controls="collapse<%= comment.id %>">
                      <div>
                        <div><%= comment.content %></div>
                        <small class="text-muted">Réponse il y a <%= Random.new.rand(1..30) %> jours</small>
                      </div>
                      <div>
                        <%= cl_image_tag(comment.user.photo.key, class: "avatar") %>
                      </div>
                    </button>
                  </h2>
                  <div id="collapse<%= comment.id %>" class="accordion-collapse collapse" aria-labelledby="heading<%= comment.id %>" data-parent="#accordionExample">
                    <div class="accordion-body">
                      <% if comment.answer %>
                      <div class="d-flex p-2 align-items-center">
                        <div>
                          <%= cl_image_tag(comment.answer.user.photo.key, class: "avatar") %>
                        </div>
                        <p class="accordion-message ml-2 mb-0">
                          <%= comment.answer.comment %>
                        </p>
                      </div>
                      <div>
                        <small class="accordion-message-timestamp mt-0" ><%= comment.answer.user.first_name %>, Nexter de <%= @city.name %> depuis <%= Random.new.rand(1..3) %> mois</small>
                      </div>
                      <% end %>
                    </div>
                  </div>
                </div>
                <% end %>
              </div>
              
          <% end %>

          <% if user_signed_in? && current_user.ask_question?(@city) %>

            <div class="card p-4 mt-4 mb-4">
              <%= render "city_comments/form", city: @city, comment: @comment %>
            </div>

          <% end %>

        </section>

      <% end %>

    </div>

    <div class="col-12 col-md-5">

      <section>

        <div id="city-data">

          <div class="d-flex">
            <div class="city-data-icon">
              <i class="fas fa-users"></i>
            </div>
            <div>
              <span class="city-data-title">Population</span> : <%= number_with_delimiter(@city.population, delimiter: " ") %> habitants
            </div>
          </div>

          <div class="d-flex mt-2">
            <div class="city-data-icon">
              <i class="fas fa-globe-europe"></i>
            </div>
            <div>
              <span class="city-data-title">Région</span> : <%= @city.region_name %><br>
              <span class="city-data-title">Département</span> : <%= @city.department_name.capitalize %>
            </div>
          </div>

          <%
            mayor_age = Date.today.year - @city.mayor_date_of_birth.year
            mayor_age -=1 if Date.today < @city.mayor_date_of_birth + mayor_age.years
          %>

          <div class="d-flex mt-2">
            <div class="city-data-icon">
              <i class="fas fa-landmark"></i>
            </div>
            <div>
              <span class="city-data-title">Maire</span> : <%= "#{@city.mayor_first_name.capitalize} #{@city.mayor_last_name.upcase} (#{mayor_age} ans)" %>
            </div>
          </div>

          <div class="d-flex mt-2">
            <div class="city-data-icon">
              <i class="fas fa-city"></i>
            </div>
            <div>
              <span class="city-data-title">Intercommunalité</span> : <%= @city.epci_name %>
            </div>
          </div>

      </section>

      <section class="mt-4">

        <div id="city-photos-carousel">
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <%= cl_image_tag @city.photos.first.key, quality: :auto, class: "city-photo" %>
              </div>
              <% @city.photos.drop(1).each do |photo| %>
                <div class="carousel-item">
                  <%= cl_image_tag photo.key, quality: :auto, class: "city-photo" %>
                </div>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>

      </section>


      <section class="mt-4">

        <div id="map"
          data-markers="<%= @markers.to_json %>"
          data-city-coordinates="<%= @city_coordinates.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>

      </section>

    </div>

  </div>

</div>

<% if @search && !current_user.city %>

  <div id="cta-block" class="d-flex align-items-center justify-content-between">
    <div>
      <span id="cta-block-title">Envie de déménager à <%= @city.name %> ?</span>
      <p class="mb-0">Faites-vous guider dans l'ensemble de vos démarches vers votre futur lieu de vie.</p>
    </div>
    
    <button id="cta-btn" type="button" class="btn btn-primary" data-toggle="modal" data-target="#cityConfirmation">
      J'y vais
    </button>
  </div>

<% elsif !@search %>

  <div id="cta-block" class="d-flex align-items-center justify-content-between">
    <div>
      <span id="cta-block-title">Besoin d'un guide ?</span>
      <p class="mb-0">Décrivez-nous vos envies pour vous aider à trouver la ville qui vous correspond le mieux.</p>
    </div>
    <%= link_to "Inspirez-moi", new_search_path, id: "cta-btn", class: "btn btn-primary" %>
  </div>      

<% end %>

<!-- City Confirmation Modal -->
<div class="modal fade" id="cityConfirmation" tabindex="-1" role="dialog" aria-labelledby="cityConfirmationTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="cityConfirmationLongTitle">Prêt pour un nouveau départ ?</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        En confirmant votre choix, vous sélectionnez <strong><%= @city.name %></strong> comme votre prochaine ville et serez accompagné à chaque étape de la concrétisation de votre projet.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Fermer</button>
        <%= link_to "Je confirme", admin_update_usercity_path(@city), method: :patch, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>